DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Status') THEN
    CREATE TYPE "Status" AS ENUM ('ACTIVE', 'INACTIVE');
  END IF;
END $$;

ALTER TABLE "users"
  ADD COLUMN IF NOT EXISTS "status" "Status" NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE "students"
  ADD COLUMN IF NOT EXISTS "status" "Status" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "photoBase64" TEXT,
  ADD COLUMN IF NOT EXISTS "faceEmbedding" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];

ALTER TABLE "teachers"
  ADD COLUMN IF NOT EXISTS "status" "Status" NOT NULL DEFAULT 'ACTIVE',
  ADD COLUMN IF NOT EXISTS "classId" INTEGER,
  ADD COLUMN IF NOT EXISTS "photoBase64" TEXT,
  ADD COLUMN IF NOT EXISTS "faceEmbedding" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];
